-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgsHn2U9HSJxO/IbZA
NoD9Huakv0/L8VVuPJBa6OfJNZigCgYIKoZIzj0DAQehRANCAASq7qQDp7eE8YHC
nqZWwheiBKvQOIrk/RIAk18MKclSRTcTcI4s8IA+T7eKwTtJU29M2K+AIMffBoq4
xXyZT8Lw
-----END PRIVATE KEY-----