workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        PRODUCT_BUNDLE_IDENTIFIER: com.replyfast.replyfast
        APP_STORE_CONNECT_ISSUER_ID: a37cd7f7-8f5e-4b21-ac6d-1c7de1a33b63
        APP_STORE_CONNECT_KEY_IDENTIFIER: 8VCVB2PJ6S

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          
          # Anahtarı geçici bir dosyaya yazıyoruz (Format hatasını engellemek için en kesin yol)
          cat <<EOF > /tmp/apple_key.p8
          -----BEGIN PRIVATE KEY-----
          MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQglL9yW7mZOnOBwNwy
          ctOkAh2OU3K8GhX+iUYNiu0haJmhRANCAAQG1zzRjFxHbLGc3/Ii9JfzHwNScswv
          CpEjyz1V42okorqjtsN98TVoPTuPG17UATpg/PAbvyOZX1/lJ/SmYmUQ
          -----END PRIVATE KEY-----
          EOF
          
          # Apple sunucularından sertifikaları çekiyoruz
          app-store-connect fetch-signing-files "$PRODUCT_BUNDLE_IDENTIFIER" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$(cat /tmp/apple_key.p8)" \
            --type IOS_APP_STORE \
            --create
          
          keychain add-certificates
      
      - name: Flutter pub get
        script: flutter pub get

      - name: Pod install
        script: |
          cd ios && pod install && cd ..

      - name: Build iOS IPA
        script: | 
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: |
          -----BEGIN PRIVATE KEY-----
          MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQglL9yW7mZOnOBwNwy
          ctOkAh2OU3K8GhX+iUYNiu0haJmhRANCAAQG1zzRjFxHbLGc3/Ii9JfzHwNScswv
          CpEjyz1V42okorqjtsN98TVoPTuPG17UATpg/PAbvyOZX1/lJ/SmYmUQ
          -----END PRIVATE KEY-----
        key_id: 8VCVB2PJ6S
        issuer_id: a37cd7f7-8f5e-4b21-ac6d-1c7de1a33b63
        submit_to_testflight: true
