workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        PRODUCT_BUNDLE_IDENTIFIER: com.replyfast.replyfast
        APP_STORE_CONNECT_ISSUER_ID: a37cd7f7-8f5e-4b21-ac6d-1c7de1a33b63
        APP_STORE_CONNECT_KEY_IDENTIFIER: 9RA3B3F29N
        BUILD_NUMBER: 1

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Set up code signing
        script: |
          #!/usr/bin/env bash
          set -e

          echo "ðŸ” Initialize keychain"
          keychain initialize

          echo "ðŸ”‘ Decode App Store Connect private key"
          echo "$APP_STORE_CONNECT_PRIVATE_KEY_BASE64" | base64 --decode > /AuthKey.p8
          chmod 600 /tmp/AuthKey.p8

          echo "ðŸ“¦ Fetch signing files"
          app-store-connect fetch-signing-files "$PRODUCT_BUNDLE_IDENTIFIER" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key /AuthKey.p8 \
            --type IOS_APP_STORE \
            --create

          echo "ðŸ“œ Add certificates"
          keychain add-certificates

      - name: Flutter pub get
        script: flutter pub get

      - name: Pod install
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS IPA
        script: |
          flutter build ipa --release --build-number=$BUILD_NUMBER

    artifacts:
      - build/ios/ipa/*.ipa
