workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_STORE_CONNECT_API_KEY: Encrypted(...) # Codemagic'te ekleniyor

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Flutter clean
        script: flutter clean

      - name: Flutter pub get
        script: flutter pub get

      - name: Build iOS IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=ios/ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: X68T5ZZN4X
        issuer_id: a37cd7f7-8f5e-4b21-ac6d-1c7de1a33b63
        submit_to_testflight: true
